sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            -
                position: bottom                             # zone in the dashboard
                type:     sonata.admin.block.admin_preview # block id
                class: col-md-12
                settings:
                    code:  admin.conference          # admin code - service id
                    icon:  fas fa-magic                     # font awesome icon
                    limit: 10
                    text:  Latest Edited Pages
                    filters:                               # filter values
                        edited:      { value: 1 }
                        _sort_by:    updatedAt
                        _sort_order: DESC

            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [sonata_page1, sonata_page2]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [sonata_page3]

            -
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Welcome to the Sonata Admin</h2>
                        <p>This is a <code>sonata.block.service.text</code> from the Block
                        Bundle, you can create and add new block in these area by configuring
                        the <code>sonata_admin</code> section.</p> <br/> For instance, here
                        a RSS feed parser (<code>sonata.block.service.rss</code>):
            -
                position: right
                type: sonata.block.service.rss
                roles: [POST_READER]
                settings:
                    title: Sonata Project's Feeds
                    url: https://sonata-project.org/blog/archive.rss                       

        groups:
            sonata_page1:
                items:
                    - admin.conference

            sonata_page2:
                items:
                    - admin.conference
                    - admin.comment

            sonata_page3:
                items:
                    - admin.comment
                     

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

